# Generated by Django 5.0.6 on 2024-06-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangam_ai', '0002_remove_jobdescription_job_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
