# Generated by Django 5.0.6 on 2024-06-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rangam_ai', '0003_prompt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobDescription',
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
    ]
