# Generated by Django 5.0.6 on 2024-06-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rangam_ai', '0004_delete_jobdescription_delete_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_input_job_description', models.TextField()),
                ('_output_response', models.TextField()),
            ],
            options={
                'db_table': 'job_description',
            },
        ),
    ]
