# Generated by Django 5.0.6 on 2024-06-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangam_ai', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobKeyResponsibilitiesRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_input_job_description', models.TextField()),
                ('_output_response', models.TextField()),
            ],
            options={
                'db_table': 'job_key_responsibilities_required',
            },
        ),
        migrations.CreateModel(
            name='JobQuestionsRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_input_job_description', models.TextField()),
                ('_output_response', models.TextField()),
            ],
            options={
                'db_table': 'job_questions_required',
            },
        ),
        migrations.CreateModel(
            name='JobSkillsRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_input_job_description', models.TextField()),
                ('_output_response', models.TextField()),
            ],
            options={
                'db_table': 'job_skills_required',
            },
        ),
    ]
